### ISSUE TITLE
hhw那边有1056和1057，但是这边解析的数据没有

### ISSUE THREAD

**Issue by forchannot** [monsterxcn/parse-hhw-abyss#1]
![image](https://user-images.githubusercontent.com/100580891/220262964-b07f6920-b2e9-4e54-b35a-3dba045315eb.png)
![image](https://user-images.githubusercontent.com/100580891/220262994-d684fe17-f994-4fe2-a200-bbeb73ea0e0f.png)
![image](https://user-images.githubusercontent.com/100580891/220263025-b7804a9e-7416-431b-95a7-4778101f7a14.png)
我记得前不久还有的，action更新了一次就没了，是被移除了吗

**Comment by monsterxcn** [comment]
https://github.com/monsterxcn/parse-hhw-abyss/blob/3c662259c873eb29cb0d594123de47631bafbb2b/README.md?plain=1#L11

那个是 Latest Beta，时间对不上，解析了也没什么意义

**Comment by monsterxcn** [comment]
不知道 Latest Live 什么时候更新，现在看 Latest Beta 的时间倒是感觉没什么问题。上次调整是由于 https://github.com/monsterxcn/nonebot-plugin-gsabyss/issues/2 那边使用 Latest Beta 数据时间有误，手动纠正的话也不好处理（深渊的怪不确定是不是一直保持 3 期一换）。

现在改了下这边，提供三份文件：

1. [`abyss.live.json`](https://cdn.monsterx.cn/bot/abyss.live.json) Latest Live 解析结果
2. [`abyss.beta.json`](https://cdn.monsterx.cn/bot/abyss.beta.json) Latest Beta 解析结果
3. [`abyss.json`](https://cdn.monsterx.cn/bot/abyss.json) 默认解析结果
   
   如果 Latest Beta 的 Schedule 时间节点同时满足以下特征的话就使用 Latest Beta 数据，否则使用 Latest Live 数据。
   
   1. 除了最后一个是 2020 年 7 月 1 日 0 点外，其余均为当天 4 点
   2. 日期均是每月 1 日和每月 16 日，按时间顺序排列并且连贯
   

如果觉得 `abyss.json` 的处理方式不对，也可以自行下载另外两份文件另外处理。
